name: Remote SSH
on:
  push:
    branches: ["main"]
  workflow_dispatch:
    input:
      target_job: 'build'

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd mie-tools
          git fetch origin
          git clean -df
          git pull
          npm ci
          npm run build
          pm2 restart mie-tools
